services:
    vich_uploader_serialization.jms_serializer.subscriber:
        class: Fresh\VichUploaderSerializationBundle\EventListener\JmsSerializerSubscriber
        public: false
        arguments:
            - "@vich_uploader.storage"
            - "@router.request_context"
            - "@annotations.cached_reader"
            - "@property_accessor"
            - "@logger"
        tags:
            - { name: jms_serializer.event_subscriber }
            - { name: monolog.logger, channel: vich_uploader_serialization }
